### ISSUE TITLE
OnStarJS Integration Collab

### ISSUE THREAD

**Issue by BigThunderSR** [metheos/OnStarJS#1]
The main things that I've hit so far are the following:

1. OnStarJS uses PNPM as the package manager, so it would be good to continue using the same. 

2. There are a couple of tests that are still failing even after I tried to rework things. 

3. When running the build, the resulting index.cjs file has some issues which prevent my being able to use it in my projects. 

Of these, item 3 is definitely the most urgent. 

For 3, if you could try to figure out a way to get the build command to create index.cjs with import statements at the beginning of the file like the original instead of the require statements that are currently being put in, that would help me avoid major rewrites on my side. 

Thanks much! 

P. S. I had made a bunch of updates related to currency of the packages being used in my fork going back a while, so you can use it as the basis for your changes if you think that might help:

https://github.com/BigThunderSR/OnStarJS

**Comment by metheos** [comment]
Sorry if this is a dumb reply, but typescript isn't my strong suit.

I'm not sure how to output a .cjs file? I also don't see build instructions in the base repo.
I compiled the typescript to ES6 with this command and it does generate .js files with import statements:
```
npx -p typescript tsc
```

I'm pretty sure I've been using pnpm with my edits. Is there something that indicates otherwise?

Which tests are failing?

**Comment by metheos** [comment]
I've pushed a couple commits that fix the failing tests. I hadn't gone through and updated them to account for the removal of the old token handler.

**Comment by metheos** [comment]
I got the build environment figured out. It generates 2 compiled files: 
index.cjs which uses require() to import modules
index.mjs which uses import to import modules

I've added @rollup/plugin-node-resolve and @rollup/plugin-commonjs to ensure there aren't any external module dependencies as well.

**Comment by metheos** [comment]
I tried to fork your repo and try some things out, but I can't seem to get home assistant to build the docker container with my changes 😵‍💫

**Comment by metheos** [comment]
The current version in my forks /dist is loading fine with all the dependencies bundled.
It's actually generating the MS tokens, but there's a weird error that doesn't exist in the uncompiled typescript. working on it now, but it's just complaining that the JWT is showing that it's not valid until 1 second in the future 🤣

```
 {"error":{"message":"JWT not active yet, now 1732234462, nbf 1732234463"},"timestamp":"2024-11-21 18:14:22"}
 ```
 
 I think we're close!

**Comment by metheos** [comment]
yeah, totally working ??
I just commented out the function that was complaining ?? I'm sure there's a better way... not sure how to configure the clock tolerance yet.
```
> onstar2mqtt@1.18.8 start
> node src/index.js

info: OnStar Config: {"onstarConfig":{"allowCommands":true,"checkRequestStatus":true,"deviceId":"dd6d04d3-1b45-4588-920b-d3ee2eb26248","onStarPin":"####","onStarTOTP":"<REDACTED>","password":"********","refreshInterval":1800000,"requestPollingIntervalSeconds":6,"requestPollingTimeoutSeconds":90,"username":"<REDACTED>","vin":"<REDACTED>"},"timestamp":"2024-11-21 18:49:29"}
info: MQTT Config: {"mqttConfig":{"host":"192.168.86.45","listAllSensorsTogether":false,"namePrefix":"","password":"********","pollingStatusTopic":"","port":1883,"prefix":"homeassistant","rejectUnauthorized":true,"tls":false,"username":"metheos"},"timestamp":"2024-11-21 18:49:29"}
info: !-- Starting OnStar2MQTT Polling --! {"timestamp":"2024-11-21 18:49:29"}
info: Requesting vehicles {"timestamp":"2024-11-21 18:49:29"}
info: Vehicle request status: {"status":"success","timestamp":"2024-11-21 18:49:29"}
info: Connecting to MQTT: {"config":{"rejectUnauthorized":true,"username":"metheos","will":{"payload":"false","retain":true,"topic":"homeassistant/<REDACTED>/available"}},"timestamp":"2024-11-21 18:49:29","url":"mqtt://192.168.86.45:1883"}
info: Connected to MQTT! {"timestamp":"2024-11-21 18:49:30"}
info: Subscribed to command topic: homeassistant/<REDACTED>/command {"timestamp":"2024-11-21 18:49:30"}
info: pollingStatusTopicState: homeassistant/<REDACTED>/polling_status/state {"timestamp":"2024-11-21 18:49:30"}
info: Polling Status Message Sensors Published! {"timestamp":"2024-11-21 18:49:30"}
info: pollingStatusTopicTF, homeassistant/<REDACTED>/polling_status/lastpollsuccessful {"timestamp":"2024-11-21 18:49:30"}
info: Polling Status TF Sensor Published! {"timestamp":"2024-11-21 18:49:30"}
info: Requesting diagnostics {"timestamp":"2024-11-21 18:49:30"}
info: Sensor Message Configs Published! {"timestamp":"2024-11-21 18:49:30"}
```

**Comment by metheos** [comment]
nope, i'm using the index.cjs the way it comes out. I published my /dist directory if you want to compare with your build result.
You do need to add the additional TOTP var to the vars/configs of onstar2mqtt

**Comment by metheos** [comment]
I published my working branch. Very minor edits required just to add the totp var.
https://github.com/metheos/onstar2mqtt/tree/metheos-onstarjs-pkce-auth

**Comment by Blue4x4Rebel** [comment]
Your branch does seem to work, but your editor reformatted a lot of things. You might want to take a look at your settings.

**Comment by metheos** [comment]
re-committed my changes with prettier disabled

**Comment by metheos** [comment]
Working great over here in HA!
Thanks @BigThunderSR 💛

**Comment by metheos** [comment]
Closing this issue!
https://github.com/BigThunderSR/onstar2mqtt/commit/ea1f9bab59ecd26f6a6f95016004ba6cfe70a47d
