### ISSUE TITLE
Addition to OnStarJs

### ISSUE THREAD

**Issue by reartvapps** [metheos/OnStarJS#2]
Can you fork the homebridge-onstar model and put this code into it so I can do further testing?

**Comment by metheos** [comment]
Please open an issue on that repo for someone familiar with it to implement. I don't have the bandwidth to learn another codebase right now.

Basically you can replace the import with the compiled index.mjs from this repo and alter the onstar.create to include the totp key.
You'll also need to update all the configs to include onStarTOTP.

replace 
```
import OnStar from "onstarjs";
```
with
```
import OnStar from "../my/path/to/onstar/index.mjs";
```

then alter the create
```
      OnStar.create({
        deviceId: this.config.deviceId,
        vin: this.config.vin,
        username: this.config.username,
        password: this.config.password,
        onStarPin: this.config.onStarPin,
        onStarTOTP: this.config.onStarTOTP,
        checkRequestStatus: false,
      }),
```

and so forth.
